export const hardWords = ["acrobat", "astronomy", "balloon", "bicycle", "bouquet", "butterfly", "camera", "candle",
    "carousel", "cartoon", "caterpillar", "chandelier", "chimney", "cinema", "comet", "discombobulate",
    "concert", "crystal", "epiphany", "diagonal", "dolphin", "eclipse", "electricity", "elephant",
    "elevator", "falcon", "fountain", "galaxy", "giraffe", "graffiti", "harmonica", "helicopter",
    "horizon", "hummingbird", "hypnotize", "insect", "irrigation", "jazz", "jewelry", "jigsaw",
    "kangaroo", "keyboard", "lighthouse", "lion", "lizard", "magnet", "maracas", "marsupial",
    "microscope", "motorcycle", "mellifluous", "mural", "neptune", "nefarious", "ostrich", "parachute",
    "parrot", "pegasus", "pendulum", "pharaoh", "photograph", "piano", "pineapple", "piranha", "polaroid",
    "poodle", "pumpkin", "pyramid", "pragmatic", "rainforest", "rhombus", "saxophone", "prosaic",
    "sculpture", "seahorse", "seashell", "siesta", "sneakers", "sphinx", "spiral", "submarine",
    "suspenders", "swallow", "tambourine", "tarantula", "telescope", "toucan", "trapeze", "trombone",
    "truffle", "turtle", "unicycle", "uranus", "velociraptor", "violin", "volcano", "wagon", "waterfall",
    "whirlpool", "wombat", "xylophone", "yacht", "yellowstone", "yogurt", "zigzag", "abstemious",
    "acrimony", "admonish", "affable", "aggrandize", "alacrity", "alleviate", "amalgamate", "ambiguous",
    "ambivalence", "ameliorate", "anachronistic", "analogous", "anomaly", "antediluvian", "antipathy",
    "apathetic", "apocryphal", "approbation", "arbitrary", "arrogate", "ascetic", "aspersion",
    "assiduous", "assuage", "audacity", "austere", "avarice", "banal", "bellicose", "benevolent",
    "benign", "bolster", "bombastic", "boorish", "burgeon", "cacophony", "cajole", "calumny",
    "camaraderie", "capricious", "carouse", "caustic", "censure", "chicanery", "circumspect",
    "clandestine", "coalesce", "cogent", "commensurate", "compendium", "complaisant", "conciliatory",
    "concomitant", "conduit", "congenial", "conjecture", "conspicuous", "contemptuous", "contentious",
    "contrite", "contumacious", "conundrum", "convivial", "copious", "corollary", "corpulent",
    "cosmopolitan", "credence", "crestfallen", "cryptic", "culpable", "cursory", "dearth", "debacle",
    "debilitate", "decorum", "deferential", "delineate", "demagogue", "denigrate", "depravity",
    "deprecate", "deride", "derivative", "derogatory", "desultory", "detrimental", "diatribe", "dictum",
    "diffident", "digress", "dilatory", "dilettante", "disaffected", "discomfit", "discordant",
    "discredit", "disdain", "disparate", "disseminate", "dissolution", "distend", "divergent", "divest",
    "divulge", "dogmatic", "duplicity", "ebullient", "eclectic", "efficacy", "effrontery", "egregious",
    "elicit", "emaciated", "emollient", "empirical", "enervate", "enfranchise", "engender", "enhance",
    "enigmatic", "enmity", "enumerate", "ephemeral", "epistolary", "equanimity", "equivocate",
    "erroneous", "erudite", "esoteric", "ethereal", "euphemism", "evanescent", "exacerbate", "exculpate",
    "exhortation", "expedient", "expedite", "expunge", "extant", "extemporaneous", "extirpate",
    "extraneous", "facetious", "fastidious", "feckless", "felicitous", "feral", "ferrous", "fervid",
    "fetid", "fictitious", "filial", "florid", "flummox", "fluvial", "foment", "forbearance",
    "formidable", "fortuitous", "fractious", "frangible", "frenetic", "friable", "frisson", "froward",
    "fructify", "fruition", "fulminate", "furtive", "gainsay", "galvanize", "gambol", "garish",
    "garrulous", "genteel", "gesticulate", "ascend", "accrue", "acumen", "adage", "adamant", "aegis",
    "aesthetic", "affluent", "alias", "altruistic", "amenable", "amiable", "amorphous", "anathema",
    "apex", "aphorism", "aplomb", "apogee", "apparition", "appease", "arbitrate", "arcane", "archaic",
    "arduous", "artifice", "ascertain", "asperity", "atrophy", "augment", "auspicious", "aversion",
    "avuncular", "axiom", "barrage", "beguile", "behemoth", "bereft", "beseech", "bibliophile", "blatant",
    "boon", "brusque", "buttress", "callous", "canard", "cantankerous", "capacious", "capitulate",
    "caricature", "cathartic", "cavalier", "celerity", "churlish", "circumscribe", "cloying",
    "compelling", "complacent", "compliant", "condone", "conflagration", "confluence", "connive",
    "connoisseur", "consensus", "contravene", "convoke", "corroborate", "culminate", "curtail", "cynical",
    "daunt", "debase", "decadent", "decimate", "defenestration", "defunct", "deleterious", "demure",
    "derision", "despot", "deterrent", "diaphanous", "dirge", "discursive"
];

export const mediumWords = ["terminal", "stable", "storm", "substance", "team", "fortress", "bat", "beach", "blank",
"cream", "crew", "detail", "interview", "darkness", "mark", "match", "pleasure", "score", "screw",
"sex", "porn", "shop", "shower", "suit", "tone", "band", "block", "bone", "calendar", "cap", "coat",
"contest", "court", "district", "finger", "asshole", "garage", "guarantee", "hole", "knees", "hook",
"implement", "layer", "lecture", "lie", "manner", "meeting", "nose", "partner", "profile", "respect",
"rice", "oatmeal", "curd", "schedule", "pool", "telephone", "tip", "bag", "battle", "bill", "bother",
"code", "curve", "dimension", "ease", "farm", "zombie", "fight", "gap", "grade", "origin", "host",
"husband", "loan", "mistake", "nail", "noise", "occasion", "package", "pause", "phrase", "race",
"relief", "sand", "sentence", "shoulder", "smoke", "stomach", "string", "tourist", "towel",
"vacation", "wheel", "arm", "aside", "associate", "bet", "blow", "border", "branch", "breast",
"brother", "buddy", "bunch", "chip", "coach", "cross", "document", "draft", "drift", "dust", "nuke",
"floor", "god", "golf", "habit", "iron", "judge", "knife", "landscape", "league", "mail", "mess",
"parent", "pattern", "pin", "pull", "push", "pound", "request", "salary", "shame", "shelter", "shoe",
"bronze", "tackle", "tank", "trust", "assist", "bake", "bar", "bell", "taco", "bike", "blame", "boy",
"brick", "closet", "clue", "collar", "comment", "conference", "devil", "diet", "fear", "fuel",
"glove", "lunch", "monitor", "mortgage", "pace", "panic", "peak", "reward", "row", "shock", "spite",
"spray", "surprise", "till", "transition", "weekend", "welcome", "yard", "alarm", "bend", "bicycle",
"bite", "blind", "bottle", "cable", "candle", "clerk", "cloud", "concert", "counter", "grandfather",
"harm", "lawyer", "load", "mirror", "neck", "pension", "plate", "ruin", "ship", "skirt", "slice",
"snow", "strok", "switch", "trash", "tune", "zone", "anger", "award", "bid", "boo", "camp", "cand",
"carpet", "champion", "channel", "comfort", "crack", "engineer", "entrance", "fault", "goblin", "elf",
"guy", "hell", "heaven", "highlight", "orc", "joke", "jury", "leg", "lip", "mate", "nerve", "passage",
"pride", "priest", "shaman", "warrior", "promise", "resort", "ring", "roof", "rope", "sail", "scheme",
"script", "python", "sock", "station", "toe", "tower", "truck", "witness", "will", "make", "goods",
"look", "help", "being", "start", "undead", "locale", "soldier", "specification", "play", "pudding",
"sunset", "change", "today", "nationality", "haircut", "show", "second", "increase", "turn", "guard",
"holder", "maine coon", "offer", "traveler", "cook", "cock", "follower", "subscriber", "dancer",
"excuse", "purchase", "deal", "drug", "secondary", "wrath", "fall", "autumn", "spring", "necessity",
"produce", "search", "spending", "talk", "dialogue", "creator", "tell", "cost", "drive", "support",
"glade", "removal", "return", "run", "reserve", "fake", "rest", "watch", "beauty", "charge", "break",
"drums", "microphone", "bass", "visit", "affect", "cover", "report", "undercover", "rise", "pursuit",
"walk", "pick", "anything", "episode", "hype", "lift", "mixer", "stop", "concern", "familiarity",
"fly", "gain", "save", "stand", "cymbal", "fail", "hello", "lead", "listener", "zeppelin", "noon",
"worry", "handler", "release", "sell", "finish", "press", "ride", "spread", "waitress", "brownie",
"deer", "display", "flow", "hit", "shoot", "touch", "cancel", "cry", "dump", "conflict", "fill",
"formality", "terminator", "jungles", "jump", "kick", "pass", "pepper", "pitch", "treat", "threat",
"damage", "bandage", "abuse", "beater", "burn", "deposit", "print", "raise", "sleep", "bush", "draw",
"withdrawal", "fix", "hire", "join", "killer", "criminal", "tap", "win", "victory", "defeat",
"attack", "claim", "drag", "drink", "vodka", "weed", "acid", "spoon", "fork", "axe", "sword",
"dagger", "guess", "wear", "wonder", "anal", "doubt", "feed", "forever", "impress", "nobody",
"repeat", "sing", "slide", "strip", "wish", "combine", "command", "dig", "divide", "bazooka", "hang",
"cliff", "hunter", "hunt", "march", "mention", "smell", "survey", "tie", "psycho", "escape", "gather",
"hate", "repair", "scratch", "sic", "slipknot", "strike", "hurt", "laugh", "lay", "static",
"absolute", "respond", "split", "strain", "struggle", "swim", "wash", "convert", "crash", "fold",
"bear", "grab", "hide", "miss", "quote", "recover", "resolve", "roll", "sushi", "sink", "slip",
"suspect", "sweep", "marathon", "swing", "click", "twist", "transistor", "casual", "concentrate",
"estimate", "miner", "prostitute", "prompt", "interpreter", "refuse", "international", "regret",
"reveal", "rush", "shake", "shift", "shine", "oxygen", "steal", "suck", "alternative", "surround",
"dare", "kebab", "delay", "junkie", "gypsy", "hurry", "invitation", "kiss", "pop", "punch", "quit",
"reply", "resist", "rip", "rub", "smile", "spell", "stretch", "tear", "bullet", "tomorrow", "wake",
"wrap", "yesterday", "container", "catch", "chain", "consideration", "impression", "improvement",
"independence", "insect", "financial", "responsible", "competitive", "comprehensive", "curious",
"educational", "environmental", "federal", "pregnant", "dependent", "impressive", "informal",
"substantial", "suspicious", "desperate", "liar", "sufficient", "thickness", "inflation", "insurance"
];

export const easyWords = ["cat", "kid", "bug", "dog", "hat", "car", "bus", "pen", "fan", "cup", "toy", "book",
"sun", "moon", "star", "tree", "flower", "grass", "lake", "river", "ocean", "fish", "bird", "duck",
"chicken", "cow", "horse", "pig", "sheep", "bread", "cake", "cheese", "egg", "juice", "biceps",
"milk", "water", "apple", "banana", "orange", "lemon", "tomato", "potato", "carrot", "onion", "chair",
"table", "call", "move", "lamp", "door", "window", "bed", "pillow", "clock", "bridge", "castle",
"cave", "circus", "clown", "desert", "dinosaur", "dragon", "fairy", "forest", "garden", "guitar",
"hiking", "island", "jacket", "jungle", "kite", "library", "mountain", "music", "nurse", "penguin",
"pirate", "pizza", "rainbow", "robot", "rocket", "sailor", "sandwich", "scissors", "snail", "snowman",
"spaceship", "spider", "squirrel", "suitcase", "superhero", "surfing", "swimming", "teddy bear",
"telescope", "train", "umbrella", "unicorn", "vase", "volcano", "wallet", "witch", "yoga", "zebra",
"different", "used", "important", "every", "large", "available", "popular", "able", "basic", "known",
"various", "difficult", "several", "united", "historical", "hot", "useful", "mental", "scared",
"additional", "emotional", "old", "political", "similar", "healthy", "medical", "traditional",
"entire", "strong", "actual", "significant", "successful", "electrical", "expensive", "intelligent",
"interesting", "poor", "happy", "cute", "helpful", "recent", "willing", "nice", "wonderful",
"impossible", "serious", "huge", "rare", "technical", "typical", "critical", "electronic",
"immediate", "aware", "global", "legal", "relevant", "accurate", "capable", "dangerous", "dramatic",
"efficient", "powerful", "foreign", "hungry", "practical", "psychological", "severe", "suitable",
"numerous", "unusual", "consistent", "cultural", "existing", "famous", "pure", "afraid", "obvious",
"careful", "latter", "unhappy", "acceptable", "aggressive", "boring", "distinct", "eastern",
"logical", "reasonable", "strict", "administrative", "automatic", "civil", "former", "massive",
"southern", "unfair", "visible", "alive", "angry", "exciting", "friendly", "lucky", "realistic",
"sorry", "ugly", "unlikely", "anxious", "inner", "pleasant", "sexual", "sudden", "terrible", "unable",
"weak", "wooden", "asleep", "confident", "conscious", "decent", "embarrassed", "guilty", "lonely",
"mad", "nervous", "odd", "remarkable", "tall", "tiny", "more", "some", "one", "all", "many", "most",
"other", "such", "even", "new", "just", "good", "any", "each", "much", "own", "great", "another",
"same", "few", "free", "right", "still", "best", "public", "human", "both", "local", "sure", "better",
"general", "specific", "enough", "long", "small", "less", "high", "certain", "little", "common",
"next", "simple", "hard", "past", "big", "possible", "particular", "real", "major", "personal",
"current", "left", "national", "least", "natural", "physical", "short", "last", "single",
"individual", "main", "potential", "professional", "lower", "open", "according", "special", "working",
"true", "whole", "clear", "dry", "easy", "cold", "commercial", "full", "low", "primary", "worth",
"necessary", "positive", "present", "close", "creative", "green", "late", "fit", "glad", "proper",
"complex", "content", "effective", "middle", "regular", "fast", "independent", "original", "wide",
"beautiful", "complete", "active", "negative", "safe", "visual", "wrong", "ago", "quick", "ready",
"straight", "white", "direct", "excellent", "extra", "junior", "pretty", "unique", "classic", "final",
"overall", "private", "separate", "western", "alone", "familiar", "official", "perfect", "bright",
"broad", "comfortable", "flat", "rich", "warm", "young", "heavy", "valuable", "correct", "leading",
"slow", "clean", "fresh", "normal", "secret", "tough", "brown", "cheap", "deep", "objective",
"secure", "thin", "chemical", "cool", "extreme", "exact", "fair", "fine", "formal", "opposite",
"remote", "total", "vast", "lost", "smooth", "dark", "double", "equal", "firm", "frequent",
"internal", "sensitive", "constant", "minor", "previous", "raw", "soft", "solid", "weird", "amazing",
"annual", "busy", "dead", "false", "round", "sharp", "thick", "wise", "equivalent", "initial",
"narrow", "nearby", "proud", "spiritual", "wild", "adult", "apart", "brief", "crazy", "prior",
"rough", "sad", "sick", "strange", "external", "illegal", "loud", "mobile", "nasty", "ordinary",
"royal", "senior", "super", "tight", "upper", "yellow", "funny", "gross", "ill", "spare", "sweet",
"upstairs", "usual", "brave", "calm", "dirty", "downtown", "grand", "honest", "loose", "male",
"quiet", "brilliant", "dear", "drunk", "empty", "female", "inevitable", "neat", "representative",
"silly", "slight", "smart", "stupid", "temporary", "weekly", "that", "this", "what", "which", "time",
"these", "work", "only", "then", "first", "money", "over", "business", "his", "game", "think",
"after", "life", "day", "home", "economy", "away", "either", "fat", "key", "training", "top", "level",
"far", "fun", "house", "kind", "future", "action", "live", "period", "subject", "mean", "stock",
"chance", "beginning", "upset", "head", "material", "salt", "appropriate", "inside", "outside",
"standard", "medium", "choice", "north", "square", "born", "capital", "shot", "front", "living",
"plastic", "express", "feeling", "otherwise", "plus", "savings", "animal", "budget", "minute",
"character", "maximum", "novel", "plenty", "select", "background", "forward", "glass", "joint",
"master", "red", "vegetable", "ideal", "kitchen", "mother", "party", "relative", "signal", "street",
"connect", "minimum", "sea", "south", "status", "daughter", "hour", "trick", "afternoon", "gold",
"mission", "agent", "corner", "east", "neither", "parking", "routine", "winter", "airline",
"designer", "dress", "emergency", "evening", "extension", "holiday", "horror", "patient", "proof",
"west", "wine", "expert", "native", "opening", "silver", "waste", "plane", "leather", "purple",
"specialist", "bitter", "incident", "motor", "pretend", "prize", "resident", "people", "history",
"way", "art", "world", "information", "map", "two", "family", "government", "health", "system",
"computer", "meat", "year", "thanks", "person", "reading", "method", "data", "food", "understanding",
"theory", "law", "literature", "problem", "software", "control", "knowledge", "power", "ability",
"economics", "love", "internet", "television", "science", "nature", "fact", "product", "idea",
"temperature", "investment", "area", "society", "activity", "story", "industry", "media", "thing",
"oven", "community", "definition", "safety", "quality", "development", "language", "management",
"player", "variety", "video", "week", "security", "country", "exam", "movie", "organization",
"equipment", "physics", "analysis", "policy", "series", "thought", "basis", "boyfriend", "direction",
"strategy", "technology", "army", "camera", "freedom", "paper", "environment", "child", "instance",
"month", "truth", "marketing", "university", "writing", "article", "department", "difference", "goal",
"news", "audience", "fishing", "growth", "income", "marriage", "user", "combination", "failure",
"meaning", "medicine", "philosophy", "teacher", "communication", "night", "chemistry", "disease",
"disk", "energy", "nation", "road", "role", "soup", "advertising", "location", "success", "addition",
"apartment", "education", "math", "moment", "painting", "politics", "attention", "decision", "event",
"property", "shopping", "student", "wood", "competition", "distribution", "entertainment", "office",
"population", "president", "unit", "category", "cigarette", "context", "introduction", "opportunity",
"performance", "driver", "flight", "length", "magazine", "newspaper", "relationship", "teaching",
"cell", "dealer", "finding", "member", "message", "phone", "scene", "appearance", "association",
"concept", "customer", "death", "discussion", "housing", "mood", "woman", "advice", "blood", "effort",
"expression", "importance", "opinion", "payment", "reality", "responsibility", "situation", "skill",
"statement", "wealth", "application", "city", "county", "depth", "estate", "foundation",
"grandmother", "heart", "perspective", "photo", "recipe", "studio", "topic", "collection",
"depression", "imagination", "passion", "percentage", "resource", "setting", "ad", "agency",
"college", "connection", "criticism", "debt", "description", "memory", "patience", "secretary",
"solution", "administration", "aspect", "attitude", "director", "personality", "psychology",
"recommendation", "response", "selection", "storage", "version", "alcohol", "argument", "complaint",
"contract", "emphasis", "highway", "loss", "membership", "possession", "preparation", "steak",
"union", "agreement", "cancer", "currency", "employment", "engineering", "entry", "interaction",
"mixture", "preference", "region", "republic", "tradition", "virus", "actor", "classroom", "delivery",
"device", "difficulty", "drama", "election", "engine", "football", "guidance", "hotel", "owner",
"priority", "protection", "suggestion", "tension", "variation", "anxiety", "atmosphere", "awareness",
"bath", "candidate", "climate", "comparison", "confusion", "construction", "elevator", "emotion",
"employee", "employer", "guest", "height", "leadership", "mall", "manager", "operation", "recording",
"sample", "transportation", "charity", "cousin", "disaster", "editor", "efficiency", "excitement",
"extent", "feedback", "homework", "leader", "mom", "outcome", "permission", "presentation",
"promotion", "reflection", "refrigerator", "resolution", "revenue", "session", "singer", "tennis",
"basket", "bonus", "cabinet", "childhood", "church", "clothes", "coffee", "dinner", "drawing", "hair",
"hearing", "initiative", "judgment", "lab", "measurement", "mode", "mud", "poetry", "police",
"possibility", "procedure", "queen", "ratio", "relation", "restaurant", "satisfaction", "sector",
"signature", "significance", "song", "tooth", "town", "vehicle", "volume", "wife", "accident",
"airport", "appointment", "arrival", "assumption", "baseball", "chapter", "committee", "conversation",
"database", "enthusiasm", "error", "explanation", "farmer", "gate", "girl", "hall", "historian",
"hospital", "injury", "instruction", "maintenance", "manufacturer", "meal", "perception", "pie",
"poem", "presence", "proposal", "reception", "replacement", "revolution", "son", "speech", "tea",
"village", "warning", "winner", "worker", "writer", "assistance", "breath", "buyer", "chest",
"chocolate", "conclusion", "contribution", "cookie", "courage", "dad", "desk", "drawer",
"establishment", "examination", "garbage", "grocery", "honey", "inspection", "inspector", "king",
"ladder", "menu", "penalty", "piano", "requirement", "salad", "sister", "supermarket", "tongue",
"weakness", "wedding", "affair", "ambition", "analyst", "assignment", "assistant", "bathroom",
"bedroom", "beer", "birthday", "celebration", "championship", "cheek", "client", "consequence",
"departure", "diamond", "dirt", "ear", "fortune", "friendship", "funeral", "gene", "girlfriend",
"indication", "intention", "lady", "midnight", "negotiation", "obligation", "passenger", "platform",
"poet", "pollution", "recognition", "reputation", "shirt", "sir", "speaker", "stranger", "surgery",
"sympathy", "tale", "throat", "trainer", "uncle", "youth", "film", "example", "stud", "air", "place",
"number", "part", "field", "back", "process", "heat", "hand", "experience", "job", "end", "point",
"type", "value", "body", "market", "guide", "interest", "state", "radio", "course", "company",
"price", "size", "list", "mind", "trade", "line", "care", "group", "risk", "word", "force", "light",
"name", "school", "amount", "order", "practice", "research", "sense", "service", "piece", "web",
"boss", "sport", "page", "term", "test", "answer", "sound", "focus", "matter", "soil", "board", "oil",
"picture", "access", "range", "rate", "reason", "sit", "demand", "exercise", "image", "case", "cause",
"coast", "age", "bad", "boat", "record", "result", "section", "building", "mouse", "cash", "class",
"nothing", "plan", "store", "tax", "side", "space", "rule", "weather", "figure", "man", "model",
"source", "earth", "program", "design", "feature", "purpose", "question", "rock", "act", "birth",
"object", "scale", "note", "profit", "rent", "speed", "style", "war", "bank", "craft", "half",
"exchange", "eye", "fire", "position", "pressure", "stress", "advantage", "benefit", "box", "frame",
"issue", "step", "cycle", "face", "item", "metal", "paint", "review", "room", "screen", "structure",
"view", "account", "ball", "discipline", "share", "balance", "bit", "black", "negro", "bottom",
"lesbian", "homosexual", "gift", "impact", "machine", "shape", "penis", "tool", "wind", "address",
"average", "career", "culture", "morning", "pot", "sign", "task", "condition", "contact", "credit",
"hope", "ice", "network", "attempt", "date", "effect", "link", "post", "voice", "challenge", "friend",
"selfie", "brush", "couple", "debate", "exit", "function", "lack", "spot", "summer", "taste", "theme",
"track", "wing", "brain", "button", "desire", "foot", "gas", "influence", "notice", "rain", "wall",
"base", "gigachad", "sigma", "damag", "distance", "pain", "staff", "sugar", "target", "text",
"author", "discount", "file", "ground", "lesson", "officer", "phase", "reference", "register", "sky",
"stage", "stick", "title", "trouble", "bowl", "campaign", "club", "edge", "idiom", "evidence",
"letter", "lock", "option", "pack", "park", "watermark", "quarter", "skin", "sort", "weight", "baby",
"carry", "dish", "factor", "fruit", "muscle", "strength", "traffic", "trip", "appeal", "chart",
"gear", "land", "log", "net", "principle", "sale", "season", "spirit", "wave", "belt", "bench",
"commission", "copy", "drop", "path", "progress", "project", "stuff", "ticket", "tour", "angle",
"blue", "breakfast", "confidence", "degree", "doctor", "dot", "dream", "duty", "essay", "father",
"fee", "finance", "limit", "luck", "mouth", "peace", "pipe", "seat", "profession", "professor",
"quantity", "reaction"
]


// const unique = JSON.stringify(Array.from(new Set(easyWords.map(str => str.toLowerCase()))));
// console.log(unique);